# Generated by Django 3.1.7 on 2021-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='welcome', verbose_name='Image')),
                ('title', models.TextField(verbose_name='Title')),
                ('animated_text', models.TextField(verbose_name='Animated Title')),
                ('paragraph', models.CharField(max_length=50, verbose_name='Paragraph')),
            ],
            options={
                'verbose_name': 'Welcome',
            },
        ),
    ]
