# Generated by Django 3.1.7 on 2021-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='paragraph',
            field=models.TextField(max_length=50, verbose_name='Paragraph'),
        ),
    ]
